name: NyaaCore
main: cat.nyaa.nyaacore.NyaaCoreLoader
description: "Code infrastructure for all NyaaCat plugins."
version: 5.0-dev
depend: [Vault]
softdepend: [Essentials, LangUtils]
authors: [RecursiveG,Librazy,cyilin]
website: "https://github.com/NyaaCat/NyaaCore"
